kind: pipeline
name: deploy
type: docker

steps:
  - name: create settings.xml
    image: md5lukas/drone-mvn-settings
    settings:
      serverSecrets:
        from_secret: maven_server_secrets
  - name: deploy
    image: maven:latest
    commands:
      - mvn deploy -B -s settings.xml

trigger:
  event:
    include:
      - push
    exclude:
      - pull_request
---
kind: pipeline
name: test-only
type: docker

steps:
  - name: test
    image: maven:latest
    commands:
      - mvn package -B

trigger:
  event:
    - pull_request