kind: pipeline
name: default
type: docker

steps:
  - name: create settings.xml
    image: md5lukas/drone-mvn-settings
    settings:
      serverSecrets:
        from_secret: maven_server_secrets
  - name: deploy
    image: maven:latest
    commands:
      - mvn deploy -B -s settings.xml

trigger:
  event:
    - push